use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // ── 1. Embed the application icon into the Windows .exe ────────
    // Only when the `windows-icon` feature is enabled (on by default).
    // CI can opt out with `--no-default-features` so that we skip the
    // `embed-resource` crate entirely (avoids needing rc.exe on the
    // build host). The icon is still loaded at runtime in `main.rs`.
    #[cfg(all(windows, feature = "windows-icon"))]
    {
        let ico_path = "assets/simple_pdf_manager.ico";
        if Path::new(ico_path).exists() {
            // Ignore errors here so that the build still succeeds even
            // if the host doesn't have rc.exe (e.g. a Linux CI box
            // cross-compiling for Windows).
            let _ = embed_resource::compile(ico_path, embed_resource::NONE);
        }
    }

    // ── 2. Embed the bundled Poppler binaries as Rust byte slices ──
    // Generates `$OUT_DIR/poppler_assets.rs` containing a const
    // `POPPLER_FILES: &[(&str, &[u8])]` with every file under
    // `assets/poppler/`. `setup.rs` `include!`s that file and extracts
    // the bytes to %LOCALAPPDATA% on first run, making the .exe fully
    // standalone (the user only needs `pdf-manager-rust.exe`).
    embed_poppler_assets();

    println!("cargo:rerun-if-changed=assets/poppler");
    println!("cargo:rerun-if-changed=build.rs");
}

#[cfg(windows)]
fn embed_poppler_assets() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let poppler_dir = Path::new(&manifest_dir).join("assets/poppler");
    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("poppler_assets.rs");

    let mut content = String::new();
    content.push_str(
        "// Auto-generated by build.rs - do not edit.\n\
         // Each entry: (relative path inside poppler/, embedded bytes)\n\
         pub const POPPLER_FILES: &[(&str, &[u8])] = &[\n",
    );

    if poppler_dir.exists() {
        collect_files(&poppler_dir, &poppler_dir, &mut content);
    } else {
        eprintln!(
            "cargo:warning=assets/poppler/ not found - PDF-to-Images will require Poppler in PATH"
        );
    }

    content.push_str("];\n");
    fs::write(&out_path, content).expect("Failed to write poppler_assets.rs");
}

#[cfg(not(windows))]
fn embed_poppler_assets() {
    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir).join("poppler_assets.rs");
    let content = "pub const POPPLER_FILES: &[(&str, &[u8])] = &[];\n";
    fs::write(&out_path, content).expect("Failed to write poppler_assets.rs");
}

#[cfg(windows)]
fn collect_files(base: &Path, dir: &Path, content: &mut String) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                collect_files(base, &path, content);
            } else if path.is_file() {
                let rel = path
                    .strip_prefix(base)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                let abs = path.to_string_lossy().replace('\\', "/");
                content.push_str(&format!(
                    "    (\"{}\", include_bytes!(\"{}\")),\n",
                    rel, abs
                ));
            }
        }
    }
}
