//! Location of the bundled `pdftoppm.exe` (Poppler for Windows).
//!
//! Strategy: we **embed** `pdftoppm.exe` and its required DLLs into the
//! Rust binary via `include_bytes!` and `include_dir!`, then on the
//! first run we extract them to `%LOCALAPPDATA%\pdf-manager-rust\poppler\`
//! (creating the directory if it doesn't exist). All subsequent calls
//! reuse that extracted folder. This way, the application is fully
//! standalone: the user only needs `pdf-manager-rust.exe`.

use std::path::PathBuf;

/// Poppler binaries embedded at compile time. The list of files is
/// generated by `build.rs` and written to `poppler_assets.rs`.
#[cfg(windows)]
mod poppler_assets {
    include!(concat!(env!("OUT_DIR"), "/poppler_assets.rs"));
}

#[cfg(not(windows))]
mod poppler_assets {
    pub const POPPLER_FILES: &[(&str, &[u8])] = &[];
}

const EXTRACT_ROOT: &str = "pdf-manager-rust";

/// Returns the path where the bundled poppler should be extracted.
/// On Windows: `%LOCALAPPDATA%\pdf-manager-rust\poppler\`
/// On other OSes: just `poppler/` next to the executable.
pub fn poppler_install_dir() -> PathBuf {
    #[cfg(windows)]
    {
        if let Ok(local) = std::env::var("LOCALAPPDATA") {
            return PathBuf::from(local).join(EXTRACT_ROOT).join("poppler");
        }
    }
    // Fallback: next to the executable.
    if let Ok(exe) = std::env::current_exe() {
        if let Some(dir) = exe.parent() {
            return dir.join("poppler");
        }
    }
    PathBuf::from("poppler")
}
/// Returns the path to `pdftoppm.exe` if it is available (either already
/// extracted, or on the system PATH). Returns `None` if not yet set up.
pub fn find_pdftoppm() -> Option<PathBuf> {
    // 1. Check the extraction dir.
    let dir = poppler_install_dir();
    let local = if cfg!(windows) {
        dir.join("pdftoppm.exe")
    } else {
        dir.join("pdftoppm")
    };
    if local.exists() {
        return Some(local);
    }

    // 2. Check next to the executable.
    if let Ok(exe) = std::env::current_exe() {
        if let Some(p) = exe.parent() {
            let candidate = p.join(if cfg!(windows) {
                "pdftoppm.exe"
            } else {
                "pdftoppm"
            });
            if candidate.exists() {
                return Some(candidate);
            }
        }
    }

    // 3. Check the system PATH.
    if let Ok(path_var) = std::env::var("PATH") {
        for entry in std::env::split_paths(&path_var) {
            let candidate = entry.join(if cfg!(windows) {
                "pdftoppm.exe"
            } else {
                "pdftoppm"
            });
            if candidate.exists() {
                return Some(candidate);
            }
        }
    }

    None
}

/// Ensures the bundled Poppler is extracted. Returns the path to
/// `pdftoppm.exe` on success, or an error if extraction failed.
/// Safe to call multiple times - it short-circuits if already done.
#[cfg(windows)]
pub fn ensure_poppler() -> anyhow::Result<PathBuf> {
    use anyhow::{anyhow, Context};
    use std::io::Write;

    if let Some(p) = find_pdftoppm() {
        return Ok(p);
    }

    let target = poppler_install_dir();
    std::fs::create_dir_all(&target)
        .with_context(|| format!("Failed to create {}", target.display()))?;

    for (name, bytes) in poppler_assets::POPPLER_FILES {
        let out = target.join(name);
        if let Some(parent) = out.parent() {
            std::fs::create_dir_all(parent)?;
        }
        // Skip extraction if file exists and has the right size.
        let needs_write = match std::fs::metadata(&out) {
            Ok(meta) => meta.len() as usize != bytes.len(),
            Err(_) => true,
        };
        if needs_write {
            let mut f = std::fs::File::create(&out)
                .with_context(|| format!("Failed to create {}", out.display()))?;
            f.write_all(bytes)?;
        }
    }

    let exe = target.join("pdftoppm.exe");
    if !exe.exists() {
        return Err(anyhow!(
            "Extracted poppler files but pdftoppm.exe is missing in {}",
            target.display()
        ));
    }
    Ok(exe)
}

#[cfg(not(windows))]
pub fn ensure_poppler() -> anyhow::Result<PathBuf> {
    find_pdftoppm().ok_or_else(|| anyhow::anyhow!("pdftoppm not found in PATH"))
}

// ── Windows: hidden child processes ────────────────────────────────
//
// `pdftoppm.exe` is a *console* application, so when we launch it from a
// GUI process the Windows OS would otherwise flash a console window every
// time the user runs "PDF -> Images". The fix is to set the
// `CREATE_NO_WINDOW` flag (0x0800_0000) on the child process, which tells
// the OS to launch it with no visible console at all.
//
// On non-Windows platforms this is a no-op.

/// Extension trait that adds a single helper to `std::process::Command`:
/// `apply_no_window_flag()`. On Windows, it sets `CREATE_NO_WINDOW` so
/// that console-based child processes (like `pdftoppm.exe`) do not pop
/// up a visible terminal window. On other platforms it is a no-op.
pub trait HiddenCommand {
    /// Make the child process invisible (no console window) on Windows.
    fn apply_no_window_flag(&mut self) -> &mut Self;
}

impl HiddenCommand for std::process::Command {
    #[cfg(windows)]
    fn apply_no_window_flag(&mut self) -> &mut Self {
        use std::os::windows::process::CommandExt;
        // CREATE_NO_WINDOW = 0x0800_0000
        self.creation_flags(0x0800_0000);
        self
    }
    #[cfg(not(windows))]
    fn apply_no_window_flag(&mut self) -> &mut Self {
        // No-op on non-Windows: there is no console window to hide.
        self
    }
}
